apiVersion: v1
kind: Namespace
metadata:
  name: molynew

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: molynew
spec:
  rules:
  - host: molynew.com
    http:
      paths: 
      - path: "/"
        pathType: Prefix
        backend:
          service: 
            name: molynew-service
            port: 
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: molynew-service
  labels:
    app: molynew
spec:
  selector:
    app: molynew
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: molynew-deployment
  labels:
    app: molynew-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: molynew
  template:
    metadata:
      namespace: molynew
      labels:
        app: molynew
    spec:
      containers:
      - name: molynew
        image: molynew/molynew-frontend:latest
        ports:
        - containerPort: 3000
  


